Name:           perl-Crypt-Cracklib
Version:        1.7
Release:        1%{?dist}
Summary:        Perl interface to Alec Muffett's Cracklib
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Crypt-Cracklib/
Source0:        http://www.cpan.org/authors/id/D/DA/DANIEL/Crypt-Cracklib-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 0:5.005
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Pod::Coverage) >= 0.19
BuildRequires:  perl(Test::More) >= 0.47
BuildRequires:  perl(Test::Pod::Coverage) >= 1.08
BuildRequires:  perl(CPAN)
BuildRequires:  cracklib-devel
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is a simple interface to the cracklib library.

%prep
%setup -q -n Crypt-Cracklib-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Crypt*
%{_mandir}/man3/*

%changelog
* Tue May 05 2015 Davide Principi <davide.principi@nethesis.it> 1.7-1
- Specfile autogenerated by cpanspec 1.78.
